title: Daniel Johnston
email: daniel@jhn.st
description: >-
  Daniel Johnston is a Software Developer from Wellington, NZ
url: "daniel.jhn.st"
github_username:  DanielJohnstonNZ

# Build settings
theme: minima
plugins:
  - jekyll-feed

